### ISSUE TITLE
expose api that can be invoked by code

### ISSUE THREAD

**Issue by mrhooray** [metaskills/mocha-phantomjs#127]
I'm thinking of writing a gulp plugin for mocha-phantomjs.

After looked at the code, it seams `bin/mocha-phantomjs` consists of two parts: cli and spawning phantomjs.

Is it a good idea to extract spawning phantomjs part from executable into lib as a library and let the executable just be a cli wrapper?

A temporary workaround I can think of is that let the gulp plugin invoke mocha-phantomjs as a child process and check output & exit code. However it's not as transparent as using a library and the plugin has to do options checking/handling which should be part of the library.

**Comment by nathanboktae** [comment]
I finally started working on this: [nathanboktae/mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core)

**Comment by nathanboktae** [comment]
[nathanboktae/mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core) is ready for consumption now. Thanks all for your feedback.
