### ISSUE TITLE
Option to disable "Error loading resource" error

### ISSUE THREAD

**Issue by heiskr** [metaskills/mocha-phantomjs#153]
Hi yall!

Have to say I love this project. So simple and easy to get setup!

But I was wondering, I keep getting "Error loading resource" all over my reporting. It'd be amazing to be able to disable that somehow,  there's like custom webfonts and SVG images that the `loadImages` option doesn't take care of.

Not sure if this is possible, if it isn't feel free to close.

Thanks!

**Comment by andreialecu** [comment]
PR #169
