### ISSUE TITLE
"SSL handshake failed" when page is using a self-signed certificate

### ISSUE THREAD

**Issue by tonysung** [metaskills/mocha-phantomjs#173]
My testing page has to use SSL for some reasons, and the certificate is self-signed.

When running mocha-phantomjs against it, I'm getting the following error:

Error loading resource https://abc.com/test/ (6). Details: SSL handshake failed
Failed to load the page. Check the url: https://abc.com/test/

I need an option to specify "--ignore-ssl-errors=true" when mocha-phantomjs calls phantomjs.

**Comment by nathanboktae** [comment]
I doubt you're seeing the issue due to your self signed cert. Ever since POODLE, people have been disabling SSL entirely, and phantomjs' default is to ONLY use SSL v3  :( so the solution is to use  `--ssl-protocol=any`. We should likely append this by default.

Right now to pass in phantomjs params is to call phantomjs directly:

```
phantomjs --ssl-protocol=any lib/mocha-phantomjs.coffee <page> <reporter> <config-as-JSON>
```

We should, however, just pass through phantomjs options like casperjs does.

**Comment by nathanboktae** [comment]
Oh in phantomjs 1.9.8, TLSv1 is the default - ariya/phantomjs#12670 . I would update your phantomjs version first. If not, you can pass `--ignore-ssl-errors` via the method I suggested.

**Comment by tonysung** [comment]
Passing in "--ssl-protocol=any" doesn't solve the problem, but setting "--ignore-ssl-errors=true" works.

**Comment by nathanboktae** [comment]
Great glad it's working for you.

**Comment by jdunck** [comment]
Sorry if this is a dumb question, but I'm running a suite with mocha-phantomjs and am unsure where `--ignore-ssl-errors` or `--ssl-protocol=any` should be added.  I'm running phantomjs 1.9.8, but am getting:

```
Error loading resource https://www.google.com/jsapi (6). Details: SSL handshake failed
```

**Comment by nathanboktae** [comment]
> (Put another way, while phantomjs offers those command line options, I don't see how to supply them via mochaPhantomJS().)

Because you can't - see #186 

However the alternative way to do this has already been stated in the thread:

```
phantomjs --ignore-resource-errors --ssl-protocol=any lib/mocha-phantomjs.coffee <page> <reporter> <config-as-JSON>
```

**Comment by redaxmedia** [comment]
Another solution is to add the self-asigned certificate to your local and CI server's <code>/usr/local/share/ca-certificates/</code> directory.

* Use command:
    <code>sudo cp foo.crt /usr/local/share/ca-certificates/foo.crt</code>

* Update the CA store:
    <code>sudo update-ca-certificates</code>

**Comment by DWboutin** [comment]
`--ssl-protocol=any --ignore-ssl-errors=true` worked for me!

**Comment by Xspirits** [comment]
Still not working here.
Doing:
`phantomjs --ssl-protocol=any --ignore-ssl-errors=true --load-images=false --debug=true index.js``

version: 1.9.8

**Comment by verishal** [comment]
Still not working 
phantomjs --disk-cache=no  --ssl-protocol=any  --web-security=false  test.js 

version: 2.1.1 
 https site not working  and i add certificate path also .But did not working.
please have idea .suggest me.

**Comment by gabrielalack** [comment]
None of the suggestions here are working for me. Same issue.
