### ISSUE TITLE
--file not working

### ISSUE THREAD

**Issue by FellowMD** [metaskills/mocha-phantomjs#177]
OSX 10.10, bash, mocha-phantomjs 3.5.3, phantomjs 1.9.8, node v0.10.34
running `mocha-phantomjs -t 30000 -R xunit --file thing.xml test.html`
I'm expecting the xunit output to go into thing.xml. Instead it comes to standard out. Additionally, it creates thing.xml, but it is an empty file.
Any ideas?

**Comment by FellowMD** [comment]
node v0.10.34

**Comment by nathanboktae** [comment]
See #161 and #114. just use:

```
mocha-phantomjs -t 30000 -R xunit --file thing.xml test.html
```

**Comment by FellowMD** [comment]
I see the problem. Are you recommending a fix? I'm confused since you pasted back to me exactly the command I'm already running

**Comment by FellowMD** [comment]
oh sorry I didn't see the redirect there.

**Comment by FellowMD** [comment]
Relevent is that there were resource errors polluting my xml, which is why I moved away from > in the first place. --ignore-resource-errors fixed the problem for me.
