### ISSUE TITLE
Tests failing in mocha-phantomjs, but not mocha

### ISSUE THREAD

**Issue by callumacrae** [metaskills/mocha-phantomjs#181]
https://travis-ci.org/Lostmyname/monkey/jobs/56906082

My tests are consistently failing in mocha-phantomjs, but they work fine when ran through the browser. How would I work out what's causing them to fail?

**Comment by nathanboktae** [comment]
I assume running locally produces the same result? Try `phantomjs --remote I debugger sport=9000 lib/mocha-phantomjs.coffee tests.html spec` for debugging.

Phantomjs definitely has its quircks. And by quircks I mean big bugs. If you are doing heavy DOM manipulation and verification, or relying on more recent DOM functionality, you might not want to use `mocha-phantomjs`. Sauce labs is really awesome if you haven't seen them.

**Comment by nathanboktae** [comment]
Closing for now. Reopen if you have more information that it is not phantomjs specific.
