### ISSUE TITLE
Can not specify phantomjs cookies-file

### ISSUE THREAD

**Issue by thomasphorton** [metaskills/mocha-phantomjs#182]
Looked through the issues and didn't see anything reported. Would it be possible to pass a flag through to phantomjs to specify --cookies-file?

http://phantomjs.org/api/command-line.html

If there isn't a technical reason for not supporting this feature, maybe all flags that aren't recognized by mocha-phantomjs should be passed through.

Thoughts? I can work on it if it isn't something that has already been discussed and shot down.

**Comment by nathanboktae** [comment]
> maybe all flags that aren't recognized by mocha-phantomjs should be passed through

Yes we should really be doing this, and would love a PR to do so.

**Comment by thomasphorton** [comment]
Cool- I'll try and schedule some time for it.

**Comment by thomasphorton** [comment]
Just hard-coding the argument into the phantomJS call gives me an unsafe access error for loading a `cookies.txt` that lives in the test directory. Looking a little deeper.

**Comment by nathanboktae** [comment]
Tracking this in #186
