### ISSUE TITLE
xunit reporter alongwith file output not working

### ISSUE THREAD

**Issue by neolegolas14** [metaskills/mocha-phantomjs#188]
Is there an issue with the xunit reporter not writing output to xml files? I am facing this as issue. When I am using json reporter and json file things are fine. As soon as I change it to xunit and xml reporter I am getting just a blank xml file and only xml console output.

**Comment by nathanboktae** [comment]
Please search for issues before filing them. This is the 4th time `xunit` and `--file` have been reported. See #114.
