### ISSUE TITLE
Getting the basic mocha html report from mocha-phantomjs

### ISSUE THREAD

**Issue by Euden** [metaskills/mocha-phantomjs#191]
Rather than using the docs report or other reporters, i'd like to get mocha's basic html report (the one that uses the nice css) from the output of mocha-phantomjs. The reason I cannot use mocha for my tests is that several of them require a headless browser to be successful.

Is there anyway to get the nice looking html out of mocha-phantomjs?

**Comment by nathanboktae** [comment]
> i'd like to get mocha's basic html report (the one that uses the nice css) from the output of mocha-phantomjs

This doesn't make any sense. The HTML reporter interacts with the DOM; all other reporters output to a console. `mocha-phantomjs` outputs to a console.

The default `spec` reporter is very nice looking.
